=== Bruviana/MineCity/Core/src/main/resources/assets/minecity/commands.dtd
<!ELEMENT minecity-commands (groups, commands)>
<!ELEMENT groups (group+)>
<!ELEMENT group (desc)>
<!ELEMENT commands (command+)>
<!ELEMENT command ((syntax,desc)|(desc,syntax)|desc|syntax)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT syntax (#PCDATA)>

<!ATTLIST minecity-commands
        modified (true|false) "true"
        add-missing (true|false) "false">

<!ATTLIST group
        id CDATA #REQUIRED
        cmd CDATA #REQUIRED
        parent CDATA #IMPLIED>

<!ATTLIST command
        id (%Commands;) #REQUIRED
        cmd CDATA #REQUIRED
        parent CDATA #IMPLIED>

<!ENTITY % Commands "%CityCommands;">
<!ENTITY % CityCommands "%CityManageCommands;|%CityPermCommands;">
<!ENTITY % CityManageCommands "city.create|city.claim|city.disclaim|city.spawn|city.rename|city.transfer|city.setspawn|city.map">
<!ENTITY % CityPermCommands "%CityAllowCommands;|%CityDenyCommands;">
<!ENTITY % CityDenyCommands "city.deny.enter|city.deny.click|city.deny.pickup|city.deny.open|city.deny.pvp|city.deny.pvc">
<!ENTITY % CityAllowCommands "city.allow.enter|city.allow.click|city.allow.pickup|city.allow.open|city.allow.pvp|city.allow.pvc">

=== Bruviana/MineCity/Core/src/main/resources/assets/minecity/commands-en.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE minecity-commands SYSTEM "https://raw.githubusercontent.com/GameModsBR/MineCity/master/Core/src/main/resources/assets/minecity/commands.dtd">
<minecity-commands modified="false" add-missing="true">
    <groups>
        <group id="root" cmd="minecity,mc">
            <desc>All MineCity commands</desc>
        </group>
        <group id="city" parent=",root" cmd="city,town,c,t">
            <desc>All city related commands</desc>
        </group>
        <group id="group" parent=",root,city" cmd="group">
            <desc>All group related commands</desc>
        </group>
        <group id="group.manager" parent="group" cmd="manager,managers">
            <desc>All group managers related commands</desc>
        </group>
        <group id="plot" parent=",city,root" cmd="plot">
            <desc>All plot related commands</desc>
        </group>
        <group id="city.allow" parent="city" cmd="allow">
            <desc>Gives permission</desc>
        </group>
        <group id="city.deny" parent="city" cmd="deny">
            <desc>Revokes permission</desc>
        </group>
        <group id="city.allow.all" parent="city.allow" cmd="all">
            <desc>Gives permission to everybody, including players who were directly prohibited</desc>
        </group>
        <group id="city.deny.all" parent="city.deny" cmd="all">
            <desc>Prohibits everybody, including players who were directly allowed</desc>
        </group>
        <group id="city.check" parent="city" cmd="check">
            <desc>Shows details about permissions</desc>
        </group>
        <group id="plot.allow" parent="plot" cmd="allow">
            <desc>Gives permission</desc>
        </group>
        <group id="plot.deny" parent="plot" cmd="deny">
            <desc>Revokes permission</desc>
        </group>
        <group id="plot.allow.all" parent="plot.allow" cmd="all">
            <desc>Gives permission to everybody, including players who were directly prohibited</desc>
        </group>
        <group id="plot.deny.all" parent="plot.deny" cmd="all">
            <desc>Prohibits everybody, including players who were directly allowed</desc>
        </group>
        <group id="plot.check" parent="plot" cmd="check">
            <desc>Shows details about permissions</desc>
        </group>
    </groups>
    <commands>
        <!-- General -->
        <command id="confirm" parent=",city,group,root,plot" cmd="confirm">
            <desc>Confirms a dangerous action</desc>
        </command>
        <command id="help" parent="city,group,root,plot" cmd="help">
            <desc>Show information about MineCity's commands</desc>
        </command>
        <command id="reload" parent="root" cmd="reload">
            <desc>Reloads the messages from the disk</desc>
        </command>

        <!-- Management -->
        <command id="city.create" parent="city" cmd="create,new">
            <desc>Creates a city</desc>
        </command>
        <command id="city.claim" parent="city" cmd="claim,expand">
            <desc>Claims a chunk to a city</desc>
        </command>
        <command id="city.disclaim" parent="city" cmd="disclaim,unclaim">
            <desc>Disclaims a chunk from a city</desc>
        </command>
        <command id="city.spawn" parent="city" cmd="go,spawn">
            <desc>Teleport you to the city</desc>
        </command>
        <command id="city.rename" parent="city" cmd="rename">
            <desc>Changes name of the city that you are inside</desc>
        </command>
        <command id="city.transfer" parent="city" cmd="transfer">
            <desc>Transfer the city to an other player</desc>
        </command>
        <command id="city.setspawn" parent="city" cmd="setspawn">
            <desc>Changes the city's spawn location</desc>
        </command>
        <command id="city.map" parent="city" cmd="map">
            <desc>Shows a map of the cities around you</desc>
        </command>
        <command id="city.delete" parent="city" cmd="delete">
            <desc>Deletes the entire city</desc>
        </command>
        <command id="city.list" parent="city" cmd="list">
            <desc>Lists all cities</desc>
        </command>

        <!-- Groups -->
        <command id="group.create" parent="group" cmd="create,new">
            <desc>Creates a new group</desc>
        </command>
        <command id="group.add" parent="group" cmd="add">
            <desc>Adds a player to a group</desc>
        </command>
        <command id="group.remove" parent="group" cmd="remove">
            <desc>Removes a player from a group</desc>
        </command>
        <command id="group.list" parent="group" cmd="list">
            <desc>Displays all city groups</desc>
        </command>
        <command id="group.info" parent="group" cmd="info">
            <desc>Displays details about a group</desc>
        </command>
        <command id="group.delete" parent="group" cmd="delete">
            <desc>Completely deletes a group from a city</desc>
        </command>
        <command id="group.add.manager" parent="group.manager" cmd="add">
            <desc>Adds a player as a group manager</desc>
        </command>
        <command id="group.remove.manager" parent="group.manager" cmd="remove">
            <desc>Demotes a player from group managers</desc>
        </command>

        <!-- Plots -->
        <command id="plot.create" parent="plot" cmd="create,new">
            <desc>Creates a new plot</desc>
        </command>
        <command id="plot.rename" parent="plot" cmd="rename">
            <desc>Renames a plot</desc>
        </command>
        <command id="plot.return" parent="plot" cmd="return">
            <desc>Returns the ownership of a plot to the city</desc>
        </command>
        <command id="plot.transfer" parent="plot" cmd="transfer">
            <desc>Transfers the ownership of a plot to an other player</desc>
        </command>
        <command id="plot.delete" parent="plot" cmd="delete">
            <desc>Deletes a plot from a city</desc>
        </command>
        <command id="plot.list" parent="plot" cmd="list">
            <desc>Lists all plots from a city</desc>
        </command>

        <!-- ========== City Permissions ========== -->
        <!-- List permissions -->
        <command id="city.perms.enter" parent="city.check" cmd="enter">
            <desc>View who can enter the city</desc>
        </command>
        <command id="city.perms.click" parent="city.check" cmd="click">
            <desc>View who can click blocks in the city</desc>
        </command>
        <command id="city.perms.pickup" parent="city.check" cmd="pickup">
            <desc>View who can pickup dropped items in the city</desc>
        </command>
        <command id="city.perms.open" parent="city.check" cmd="open">
            <desc>View who can open containers in the city</desc>
        </command>
        <command id="city.perms.pvp" parent="city.check" cmd="pvp">
            <desc>View who can attack other players in the city</desc>
        </command>
        <command id="city.perms.pvc" parent="city.check" cmd="pvc">
            <desc>View who can attack creatures in the city</desc>
        </command>
        <command id="city.perms.modify" parent="city.check" cmd="modify">
            <desc>View who can do structural modifications to the city</desc>
        </command>

        <!-- Default permissions -->
        <command id="city.perms" parent="city" cmd="perms,permissions,perm">
            <desc>Displays all city permissions</desc>
        </command>
        <command id="city.allow.enter" parent="city.allow" cmd="enter">
            <desc>Allows players to enter the city</desc>
        </command>
        <command id="city.allow.click" parent="city.allow" cmd="click">
            <desc>Allows players to click on clickable blocks, like doors, buttons and levelers</desc>
        </command>
        <command id="city.allow.pickup" parent="city.allow" cmd="pickup">
            <desc>Allows players to pickup dropped items</desc>
        </command>
        <command id="city.allow.open" parent="city.allow" cmd="open">
            <desc>Allows players to open container like chests, furnaces, frames</desc>
        </command>
        <command id="city.allow.pvp" parent="city.allow" cmd="pvp">
            <desc>Allows players to attack other players</desc>
        </command>
        <command id="city.allow.pvc" parent="city.allow" cmd="pvc">
            <desc>Allows players to attack creatures</desc>
        </command>
        <command id="city.allow.modify" parent="city.allow" cmd="modify">
            <desc>Allows players to do structural modifications</desc>
        </command>
        <command id="city.deny.enter" parent="city.deny" cmd="enter">
            <desc>Deny players to enter the city, will not affect players who are already inside.</desc>
        </command>
        <command id="city.deny.click" parent="city.deny" cmd="click">
            <desc>Deny players to click on clickable blocks, like doors, buttons and levelers</desc>
        </command>
        <command id="city.deny.pickup" parent="city.deny" cmd="pickup">
            <desc>Deny players to pickup dropped items</desc>
        </command>
        <command id="city.deny.open" parent="city.deny" cmd="open">
            <desc>Deny players to open container like chests, furnaces, frames</desc>
        </command>
        <command id="city.deny.pvp" parent="city.deny" cmd="pvp">
            <desc>Deny players to attack other players</desc>
        </command>
        <command id="city.deny.pvc" parent="city.deny" cmd="pvc">
            <desc>Deny players to attack creatures</desc>
        </command>
        <command id="city.deny.modify" parent="city.deny" cmd="modify">
            <desc>Stop players from doing structural modifications</desc>
        </command>

        <!-- All permissions -->
